### PR TITLE
La/upstream update

### PR DESCRIPTION
**Pull request by loriashwood-quizlet**
### Ticket
Link to ticket: No linked ticket Related to MAGIC-2057

### What has been done
- merged the the upstream Leaflet develop branch with local upstream_update and fixed a typo
- 

### How to test
- 
- 

### Todo
- [ ] 
- [ ] 

### Notes
- 
-

### CODE REVIEW

**Review by pfmmfp — APPROVED** [review]
I see this brings from the `develop` branch of the original repo [this change](https://github.com/quizlet/Leaflet.draw/pull/2/files#diff-e8f9b439f8ee9dd3aa2b3f43d54d5439L40). That looks good.

I might be wrong but I think all other files have been removed from our fork to avoid having docs, dist and build files delivered into our production bundle. If the intention is to bring them in to make it easier on future upstream updates, that sounds good to me, but we should check on the JS output.

Otherwise, what I did last time was to [rollback the delete](https://github.com/quizlet/Leaflet.draw/commit/4cd28ff6489ca3ceb7133dae7f72a6206ea101ce), so that the upstream changes make more sense, and then [deleted again after merging](https://github.com/quizlet/Leaflet.draw/commit/fd6a2954fa53b19dac6c559442752d30a546fd1c)

**Comment by loriashwood-quizlet** [comment]
@pfmmfp as discussed, I'll merge this PR and remove unneeded files in a separate PR. Thanks

**Comment by turadg** [comment]
I don't follow why we're removing and adding them again. What harm is it to leave these supporting files in the repo?

**Comment by loriashwood-quizlet** [comment]
The concern is about the weight of all the build files and the possible effects on performance. @pfmmfp can argue his point on this.

**Comment by pfmmfp** [comment]
I don't have strong points on keep deleting them. At the time, I just wanted to keep the build with the minimum changes, to be cautious. But as I've said, if the intention is to keep them, it sounds like a good idea, we'll just need to make sure there is no other reason.

**Pull request merged**
